### ISSUE TITLE
Custom template not loaded

### ISSUE THREAD

**Issue by vincic** [ianderrington/mkdocs_slides#2]
Extracted the template and tried to change it but it is not used. 
Font_size is not applied either.

I am running mkdocs in Docker
```Dockerfile
FROM squidfunk/mkdocs-material

RUN pip install mkdocs-glightbox mkdocs-literate-nav mkdocs-slides
```

With `docker run -u ${UID}:${GID} --rm -it -p 8000:8000 -v ${PWD}:/docs ${IMAGE_NAME}`

My folder structure 
```
docs
layouts
overrides
```
mkdocs snippet
```yaml
plugins:
  - slides:
      font_size: 64px
      template: layouts/slide_template.html
```
